### ISSUE TITLE
Variation of configurations for Windows

### ISSUE THREAD

**Issue by raulso61** [lytex/vscode-setup#1]
If we want the same code to be compatible with Windows is necessary to add  \" instead of  '  both before and after writing ${file}  i.e. ```"text": "run \"${file}\" \n"```

https://github.com/lytex/vscode-setup/blob/b2d07b91c9966c549a4ff494b8532075ccf11989/keybindings.json#L103

**Comment by lytex** [comment]
I attach a custom settings.json for a conda setup in Windows from @raulso61 :
[settings.txt](https://github.com/lytex/vscode-setup/files/4383888/settings.txt)
